source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib', require: 'sinatra/reloader'
gem 'rack-test'
gem 'sequel'
gem 'sqlite3'
gem 'pry'
gem 'minitest'
gem 'rake'
gem 'database_cleaner'
gem 'shotgun'
